% CCSI APC Framework
% Pseudo-code for simulating the 'Plant' / 'High-fidelity Model'
%
% The following variables are required to be present in the WORKSPACE
% before invoking this script -
%
% 1. u_plant  - Vector containing values of input ports which need to be 
%               communicated to the plant for next-step plant-calculations
%               :: u[k]
% 2. t_plant  - Plant's current time-stamp (scalar), typically same as 
%               simulation time :: t[k]
% 3. Ts_plant - Sampling time-interval for the plant. May not be used for
%               discrete-time plants :: Ts
%
% The following variables are generated by this script -
%
% 4. y_plant  - Vector containing values of output ports at next-step :: 
%               y_plant[k+1]
%
% Notes - 
% 1. It is assumed that the plant preserves its state information and
%    hence the states (x_plant / y_plant) may NOT be provided.
% 2. The inputs/outputs to/from the control-model/DRM variables are mapped 
%    through model indices - u_idx and y_idx
% 3. Furthermore, I/O to/from the controller variables are mapped through
%    controller indices - uc_idx and yc_idx
% 4. u_plant and y_plant are column vectors

% Code written and developed by:
% Priyadarshi Mahapatra, PhD
% URS Corporation / National Energy Technology Laboratory
% 13 Sept 2013
%
% -------------------------------------------------------------------------
% Specific instructions for ACM-based pH_Reactor example -
%
% Make sure pH-Reactor simulink model is defined and initialized. If not, 
% the following steps may be used as a guide -
% 1. Setup the ACM (.acmf) file. Make sure the simulation has converged to
%    a steady-state. Take note of the relevant I/O variable names and their
%    nominal values.
% 2. Setup the ACM-embedded Simulink model (.mdl). Associate the ACM-block
%    with the simulation model. Choose the 'plant' input/output variables
%    as noted earlier. Check/rectify number of inputs/outputs in Demux/Mux
%    blocks and make/remove connections as required. Set the communication
%    time (typically same as Ts_plant). Save the model as pH_Neut.mdl.

up = u_plant;
% TBD - Backup variable 'up' before overwriting

sim('pH_Neut',[t_plant t_plant+Ts_plant],simset('FixedStep',Ts_plant));

y_plant = yp(end,:)';
